### ISSUE TITLE
import label_map_util出错

### ISSUE THREAD

**Issue by ygowill** [Honlan/wechat_jump_tensorflow#6]
下载了代码想尝试一下，但是在运行的时候出现了这个错误，想问问解决方案。错误提示如下：
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from utils import label_map_util
  File "/Users/qinkai/Desktop/wechat_jump_tensorflow-master/tensorflow/utils/label_map_util.py", line 208, in <module>
    options=None, file=DESCRIPTOR),
  File "/Users/qinkai/anaconda3/envs/myPythonEnv/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by Honlan** [comment]
test.py内容是和wechat_auto_jump.py一样的吗？

**Comment by ygowill** [comment]
稍微修改了一些，将循环去掉了，将跳跃函数去掉了，同时将截图的地址换成了固定的图片，加入了绘制检测框并显示的函数，其他的没有改动

**Comment by Honlan** [comment]
做这些修改之前，一样的代码，在你的电脑上能运行吗

**Comment by ygowill** [comment]
后来尝试了一下，也是这个错误

**Comment by Retty-M** [comment]
同样的错误代码,没有改动源码,原因是什么啊

**Comment by TheSmallYing** [comment]
python simple.py
Traceback (most recent call last):
  File "simple.py", line 4, in <module>
    import cv2
  File "/Library/Python/2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Library/Python/2.7/site-packages/cv2/cv2.so, 2): Library not loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
  Referenced from: /Library/Python/2.7/site-packages/cv2/.dylibs/libavcodec.57.107.100.dylib
  Reason: image not found


这是缺少什么运行环境吗？

**Comment by zjmeng2006** [comment]
Traceback (most recent call last):
  File "wechat_auto_jump.py", line 7, in <module>
    from utils import label_map_util
  File "F:\GitHub\wechat_jump_tensorflow-master\tensorflow\utils\label_map_util.
py", line 208, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
同样的错误！

**Comment by zjmeng2006** [comment]
tensorflow由1.2升级到1.4后，可正常运行了。

**Comment by Honlan** [comment]
我的环境：
- macos：10.12.6
- python：3.6
- opencv：3.4.0.12
- tensorflow：1.4.0
