### ISSUE TITLE
运行simple.py报错

### ISSUE THREAD

**Issue by theLittleShadow** [Honlan/wechat_jump_tensorflow#7]
python simple.py
Traceback (most recent call last):
  File "simple.py", line 4, in <module>
    import cv2
  File "/Library/Python/2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Library/Python/2.7/site-packages/cv2/cv2.so, 2): Library not loaded: /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
  Referenced from: /Library/Python/2.7/site-packages/cv2/.dylibs/libavcodec.57.107.100.dylib
  Reason: image not found

**Comment by Honlan** [comment]
可以在python里先import cv2试一下，看opencv装好了没
